### ISSUE TITLE
Better Docs

### ISSUE THREAD

**Issue by ArlinJae** [samrobbins85/general-notes#41]
Hey bud,
Came across the project and really liked the whole way you pulled it off... I wanted to folk it and use it for my own notes.

Just one request - could you please make better docs? I'm having a bit of a tough time figuring out the way you've coded this. No need to do anything to hi-fi just a basic para or two about the usage of this.

Cheers,
Jai

**Comment by samrobbins85** [comment]
Yeah of course, didn't expect people to really use it so didn't make any, but I'll make some in the next few days and close this when I have

**Comment by ArlinJae** [comment]
Ah, of course. Kinda new to JS so I would die without the documentation. Thanks a lot and sorry for making you spend time on this.

Also, I really like the whole interface you've made. I've been looking for a similar project on Github but this is the best so far.

Cheers and thanks again,

Jai

**Comment by ArlinJae** [comment]
Hey,
Just wanted to follow up on this request. Thanks a ton again.

Cheers,
J

**Comment by samrobbins85** [comment]
Pretty busy right now, a different solution might be better for you
